.*: Assembler messages:
.*:4: Error: branch to misaligned address \(0x1\)
.*:5: Error: branch address range overflow \(0xffffffc\)
.*:6: Error: branch to misaligned address \(0xfffffff\)
.*:6: Error: branch address range overflow \(0xfffffff\)
.*:7: Error: branch address range overflow \(0x10000000\)
.*:8: Error: branch to misaligned address \(0x10000003\)
.*:8: Error: branch address range overflow \(0x10000003\)
