.*Assembler messages:
.*:9: Warning: relaxed out-of-range branch into a jump
.*:12: Warning: relaxed out-of-range branch into a jump
.*:15: Warning: relaxed out-of-range branch into a jump
.*:18: Warning: relaxed out-of-range branch into a jump
.*:23: Warning: relaxed out-of-range branch into a jump
.*:26: Warning: relaxed out-of-range branch into a jump
.*:29: Warning: relaxed out-of-range branch into a jump
.*:32: Warning: relaxed out-of-range branch into a jump
