.*.s: Assembler messages:
.*.s:501: Warning: divide by zero
.*.s:514: Warning: divide by zero
.*.s:1430: Warning: divide by zero
.*.s:2509: Warning: branch bge is always true
.*.s:2521: Warning: branch bgeu is always true
.*.s:2596: Warning: branch ble is always true
.*.s:2611: Warning: branch bleu is always true
.*.s:2617: Warning: branch bleu is always true
.*.s:2620: Warning: branch bleu is always true
