.*: Assembler messages:
.*:11: Warning: Dangerous use of FP registers in fp64 when module is fp32
.*:11: Warning: Dangerous use of FP registers in fp64 when module is fp32
.*:11: Warning: Dangerous use of FP registers in fp64 when module is fp32
.*:16: Warning: Dangerous use of FP registers in fp64 when module is fp32
.*:16: Warning: Dangerous use of FP registers in fp64 when module is fp32
.*:16: Warning: Dangerous use of FP registers in fp64 when module is fp32
