.*: Assembler messages:
.*:11: Warning: Dangerous use of FP registers in fp32 when module is fp64
.*:11: Warning: Dangerous use of FP registers in fp32 when module is fp64
.*:11: Warning: Dangerous use of FP registers in fp32 when module is fp64
.*:16: Warning: Dangerous use of FP registers in fp32 when module is fp64
.*:16: Warning: Dangerous use of FP registers in fp32 when module is fp64
.*:16: Warning: Dangerous use of FP registers in fp32 when module is fp64
