.*: Assembler messages:
.*:3: Error: opcode not supported on this processor: mips(32|64)r7 \(mips(32|64)r7\) `tlbginv'
.*:4: Error: opcode not supported on this processor: mips(32|64)r7 \(mips(32|64)r7\) `tlbginvf'
.*:5: Error: opcode not supported on this processor: mips(32|64)r7 \(mips(32|64)r7\) `tlbgp'
.*:6: Error: opcode not supported on this processor: mips(32|64)r7 \(mips(32|64)r7\) `tlbgr'
.*:7: Error: opcode not supported on this processor: mips(32|64)r7 \(mips(32|64)r7\) `tlbgwi'
.*:8: Error: opcode not supported on this processor: mips(32|64)r7 \(mips(32|64)r7\) `tlbgwr'
