.*.s: Assembler messages:
.*.s:502: Warning: divide by zero
.*.s:515: Warning: divide by zero
.*.s:1431: Warning: divide by zero
.*.s:2510: Warning: branch bge is always true
.*.s:2522: Warning: branch bgeu is always true
.*.s:2597: Warning: branch ble is always true
.*.s:2612: Warning: branch bleu is always true
.*.s:2618: Warning: branch bleu is always true
.*.s:2621: Warning: branch bleu is always true
