.*.s: Assembler messages:
.*.s:494: Warning: divide by zero
.*.s:507: Warning: divide by zero
.*.s:1423: Warning: divide by zero
.*.s:2494: Warning: branch bge is always true
.*.s:2506: Warning: branch bgeu is always true
.*.s:2581: Warning: branch ble is always true
.*.s:2596: Warning: branch bleu is always true
.*.s:2602: Warning: branch bleu is always true
.*.s:2605: Warning: branch bleu is always true
