.*: Assembler messages:
.*:3: Error: opcode not supported on this processor: mips(32|64)r7 \(mips(32|64)r7\) `tlbinv'
.*:4: Error: opcode not supported on this processor: mips(32|64)r7 \(mips(32|64)r7\) `tlbinvf'
.*:5: Error: opcode not supported on this processor: mips(32|64)r7 \(mips(32|64)r7\) `tlbp'
.*:6: Error: opcode not supported on this processor: mips(32|64)r7 \(mips(32|64)r7\) `tlbr'
.*:7: Error: opcode not supported on this processor: mips(32|64)r7 \(mips(32|64)r7\) `tlbwi'
.*:8: Error: opcode not supported on this processor: mips(32|64)r7 \(mips(32|64)r7\) `tlbwr'
