.*.s: Assembler messages:
.*.s:503: Warning: divide by zero
.*.s:516: Warning: divide by zero
.*.s:1432: Warning: divide by zero
.*.s:2511: Warning: branch bge is always true
.*.s:2523: Warning: branch bgeu is always true
.*.s:2598: Warning: branch ble is always true
.*.s:2613: Warning: branch bleu is always true
.*.s:2619: Warning: branch bleu is always true
.*.s:2622: Warning: branch bleu is always true
