.*.s: Assembler messages:
.*.s:592: Warning: divide by zero
.*.s:605: Warning: divide by zero
.*.s:1579: Warning: divide by zero
.*.s:2658: Warning: branch bge is always true
.*.s:2670: Warning: branch bgeu is always true
.*.s:2745: Warning: branch ble is always true
.*.s:2760: Warning: branch bleu is always true
.*.s:2766: Warning: branch bleu is always true
.*.s:2769: Warning: branch bleu is always true
