.*.s: Assembler messages:
.*.s:493: Warning: divide by zero
.*.s:506: Warning: divide by zero
.*.s:1103: Warning: divide by zero
.*.s:1763: Warning: branch bge is always true
.*.s:1775: Warning: branch bgeu is always true
.*.s:1847: Warning: branch ble is always true
.*.s:1862: Warning: branch bleu is always true
.*.s:1868: Warning: branch bleu is always true
.*.s:1871: Warning: branch bleu is always true
