.*: Assembler messages:
.*:3: Error: opcode not supported on this processor: nanomips(32|64)r6 \(nanomips(32|64)r6\) `tlbinv'
.*:4: Error: opcode not supported on this processor: nanomips(32|64)r6 \(nanomips(32|64)r6\) `tlbinvf'
.*:5: Error: opcode not supported on this processor: nanomips(32|64)r6 \(nanomips(32|64)r6\) `tlbp'
.*:6: Error: opcode not supported on this processor: nanomips(32|64)r6 \(nanomips(32|64)r6\) `tlbr'
.*:7: Error: opcode not supported on this processor: nanomips(32|64)r6 \(nanomips(32|64)r6\) `tlbwi'
.*:8: Error: opcode not supported on this processor: nanomips(32|64)r6 \(nanomips(32|64)r6\) `tlbwr'
