.*: Assembler messages:
.*:3: Error: opcode not supported on this processor: nanomips(32|64)r6 \(nanomips(32|64)r6\) `tlbginv'
.*:4: Error: opcode not supported on this processor: nanomips(32|64)r6 \(nanomips(32|64)r6\) `tlbginvf'
.*:5: Error: opcode not supported on this processor: nanomips(32|64)r6 \(nanomips(32|64)r6\) `tlbgp'
.*:6: Error: opcode not supported on this processor: nanomips(32|64)r6 \(nanomips(32|64)r6\) `tlbgr'
.*:7: Error: opcode not supported on this processor: nanomips(32|64)r6 \(nanomips(32|64)r6\) `tlbgwi'
.*:8: Error: opcode not supported on this processor: nanomips(32|64)r6 \(nanomips(32|64)r6\) `tlbgwr'
