.*.s: Assembler messages:
.*.s:493: Warning: divide by zero
.*.s:506: Warning: divide by zero
.*.s:1209: Warning: divide by zero
.*.s:1982: Warning: branch bge is always true
.*.s:1994: Warning: branch bgeu is always true
.*.s:2066: Warning: branch ble is always true
.*.s:2081: Warning: branch bleu is always true
.*.s:2087: Warning: branch bleu is always true
.*.s:2090: Warning: branch bleu is always true
