.*.s: Assembler messages:
.*.s:496: Warning: divide by zero
.*.s:509: Warning: divide by zero
.*.s:1425: Warning: divide by zero
.*.s:2496: Warning: branch bge is always true
.*.s:2508: Warning: branch bgeu is always true
.*.s:2583: Warning: branch ble is always true
.*.s:2598: Warning: branch bleu is always true
.*.s:2604: Warning: branch bleu is always true
.*.s:2607: Warning: branch bleu is always true
