.*: Assembler messages:
.*:3: Error: opcode not supported on this processor: nms1 \(32r6s\) `tlbinv'
.*:4: Error: opcode not supported on this processor: nms1 \(32r6s\) `tlbinvf'
.*:5: Error: opcode not supported on this processor: nms1 \(32r6s\) `tlbp'
.*:6: Error: opcode not supported on this processor: nms1 \(32r6s\) `tlbr'
.*:7: Error: opcode not supported on this processor: nms1 \(32r6s\) `tlbwi'
.*:8: Error: opcode not supported on this processor: nms1 \(32r6s\) `tlbwr'
