.*: Assembler messages:
.*:7: Error: operand 3 out of range `addiu \$a0,\$a0,\(1b-2b\)'
.*:8: Error: operand 3 out of range `addiu \$a0,\$a0,\(2b-1b\)'
.*:9: Error: Operand 3 out of range `addiu \$r4,\$r0,-65540
.*:10: Error: Operand 3 out of range `addiu \$r4,\$r0,65540
.*:11: Error: Operand 3 out of range `addiu \$r4,\$r4,-65540
.*:12: Error: Operand 3 out of range `addiu \$r4,\$r4,65540
.*:13: Error: Operand 3 out of range `addiu \$r4,\$r0,-65540
.*:14: Error: Operand 3 out of range `addiu \$r4,\$r0,65540
